run: Persona Superheroe Villano inicio
inicio: main.cpp Persona.o Superheroe.o Villano.o 
	g++ main.cpp Persona.o Superheroe.o Villano.o -o main
Villano: Villano.cpp Villano.h
	g++ Villano.cpp -c
Superheroe: Superheroe.cpp Superheroe.h
	g++ Superheroe.cpp -c
Persona: Persona.cpp Persona.h
	g++ Persona.cpp -c