run: Vehiculo Microbus inicio
inicio: main.cpp Vehiculo.o Microbus.o
	g++ main.cpp Microbus.o Vehiculo.o -o main
Microbus: Microbus.cpp Microbus.h
	g++ Microbus.cpp -c
Vehiculo: Vehiculo.cpp Vehiculo.h
	g++ Vehiculo.cpp -c